version: '3.3'
services:
  client:
    build: .
    ports:
      - '1234:1234'
    volumes:
      - '.:/app'
    container_name: crime-camera-client
    environment:
      - "RTSPTOWEB_HOST_AND_PORT=${HOSTNAME}:8083"
      - "API_HOST_AND_PORT=${HOSTNAME}:3000"

